// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGZ6fXkHx2534bPtQTF9INhJibhkWXx4',
    appId: '1:587316204204:web:c6b656fdf83a41c2058509',
    messagingSenderId: '587316204204',
    projectId: 'flutter-app-firebase-a46b2',
    authDomain: 'flutter-app-firebase-a46b2.firebaseapp.com',
    storageBucket: 'flutter-app-firebase-a46b2.appspot.com',
    measurementId: 'G-N7LEPW8YM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpE347G8DnVRz4vqb4ZMPcMekTxvv0Y_Q',
    appId: '1:587316204204:android:72045ce8bca9c4ba058509',
    messagingSenderId: '587316204204',
    projectId: 'flutter-app-firebase-a46b2',
    storageBucket: 'flutter-app-firebase-a46b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCbGI5jNcmyKHm-p7dVxK1Z5iNHH6qHQ',
    appId: '1:587316204204:ios:f5ecbf7d4f488147058509',
    messagingSenderId: '587316204204',
    projectId: 'flutter-app-firebase-a46b2',
    storageBucket: 'flutter-app-firebase-a46b2.appspot.com',
    iosClientId: '587316204204-tvdep6viq1nfa18bpsk81atl1e1aui4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppFirebase',
  );
}
