name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.1

      - name: Cache Dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            /opt/hostedtoolcache/flutter
            /Users/runner/hostedtoolcache/flutter
            /Users/runner/.pub-cache
          key: ${{ runner.os }}-build
          restore-keys: |
            ${{ runner.os }}-build

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: stable
          cache: true

      - name: Build Website
        run: flutter build web --base-href /flutter-app-firebase/

      - name: Publish Website
        if: github.repository == 'jaredsburrows/flutter-app-firebase' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: "Github Actions"
          user_email: "action@github.com"
