name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
  JAVA_VERSION: 19

jobs:
  build:
    name: Build
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.5.2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Cache Dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ios/Pods
            /opt/hostedtoolcache/flutter
            /Users/runner/hostedtoolcache/flutter
            /Users/runner/.pub-cache
          key: ${{ runner.os }}-build
          restore-keys: |
            ${{ runner.os }}-build

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Run Build
        uses: gradle/gradle-build-action@v2.5.1

      - name: Configure Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable
          cache: true

      - name: Build Android
        run: flutter build apk --debug

      - name: Build iOS
        run: flutter build ios --debug --no-codesign

      - name: Build Website
        run: flutter build web --base-href /flutter-app-firebase/

      - name: Publish Website
        if: github.repository == 'jaredsburrows/flutter-app-firebase' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: "Github Actions"
          user_email: "action@github.com"
